dist: bionic

language: go

go:
  - 1.13

sudo: required

env:
  matrix:
    - MODULE=webapp
    - MODULE=sandbox
    - MODULE=unsafebox

services:
  - docker

script:
  - make -C $MODULE docker-build
